server:
  port: 8090
  servlet:
    context-path: /transport-api

spring:
  application:
    # 应用名称
    name: nfp-transport
  profiles:
    # 环境配置
    active: local
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz91m951i50ajyb38o.mysql.rds.aliyuncs.com:3306/xfb_mall_wh?useUnicode=true&characterEncoding=utf-8&connectionCollation=utf8mb4_general_ci&useSSL=false&serverTimeZone=GMT+8&allowMultiQueries=true&zeroDateTimeBehavior=round
    username: xfb_wh
    password: LxR4cbMqga2Yx4qmU1xuetKW
    initialSize: 10
    minIdle: 10
    maxActive: 500
    maxWait: 9000
    timeBetweenEvictionRunsMillis: 900000
    minEvictableIdleTimeMillis: 1200000
    removeAbandonedTimeout: 300
    validationQuery: SELECT 'X'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    removeAbandoned: true
    logAbandoned: true
    poolPreparedStatements: false
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20


